params:
  boosting_type: gbdt
  objective: binary
  learning_rate: 0.05
  lambda_l1: 0.001
  lambda_l2: 0.001
  seed: 42
  verbose: -1
  n_jobs: -1
path: resources/models/
name: lightgbm
results: 5fold-embedding-lightgbm
early_stopping_rounds: 100
num_boost_round: 30000
verbose_eval: 100