hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - features: featurize
  - experiment: wandb
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled